version: "3.7"
services:
    db:
        image: postgres:alpine
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
        -   "5432:5432"
    web:
        build: .
        container_name: twitter_clone
        restart: always
        depends_on:
        -   db
        environment:
            HOST: ${HOST}
            PORT: ${PORT}
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_URI: ${DATABASE_URI}
        ports:
        -   "50000:50000"